theme: jekyll-theme-slate
title: Virginia Rutten
description: graduate student at the Gatsby Computational Neuroscience Unit
baseurl: "/blob/master"
url: "https://github.com/vrutten/vrutten.github.io"
